### ISSUE TITLE
Run with Local Docker Container RabbitMQ Service

### ISSUE THREAD

**Issue by ric-evans** [WIPACrepo/MQClient-RabbitMQ#6]
Found in https://github.com/WIPACrepo/MQClient-RabbitMQ/pull/5

Running with a Docker container had problems connecting on my machine: `pika.exceptions.IncompatibleProtocolError: StreamLostError: ('Transport indicated EOF',)`

This includes the docker container running in `run-with-wipactel-local.sh` (and the commented-out container).

Priority unknown, this may not be worth the trouble if we plan on having a remote service. **It could also just be my machine.**

**Comment by ric-evans** [comment]
running with `docker run -d -p 8084:5672 deadtrickster/rabbitmq_prometheus` (`docker run -d --rm -it -p 15672:15672 -p 5672:5672 rabbitmq:3-management` was similar) _without local wipactel_ produced:
 ```
2021-11-09 17:02:17 DellXPS-8BX90Z2 root[569781] DEBUG [__init__()] Initializing pub. (('localhost', 'queue1'); {})
2021-11-09 17:02:17 DellXPS-8BX90Z2 root[569781] DEBUG [connect()] Pub connecting...
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.adapters.utils.io_services_utils[569781] ERROR Socket EOF; <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 48028)>
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.adapters.base_connection[569781] ERROR Transport indicated EOF.
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.adapters.base_connection[569781] ERROR connection_lost: StreamLostError: ('Transport indicated EOF',)
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.connection[569781] ERROR Probably incompatible Protocol Versions
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.adapters.utils.connection_workflow[569781] ERROR AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.adapters.utils.connection_workflow[569781] ERROR AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - None.
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.adapters.utils.connection_workflow[569781] ERROR AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - None
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.adapters.blocking_connection[569781] ERROR Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - None
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.adapters.blocking_connection[569781] ERROR Error in _create_connection().
Traceback (most recent call last):
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.IncompatibleProtocolError: StreamLostError: ('Transport indicated EOF',)
2021-11-09 17:02:17 DellXPS-8BX90Z2 root[569780] DEBUG Creating new MessageGeneratorContext instance.
2021-11-09 17:02:17 DellXPS-8BX90Z2 root[569780] DEBUG [__init__()] Initializing sub. (('localhost', 'queue1'); {})
2021-11-09 17:02:17 DellXPS-8BX90Z2 root[569780] DEBUG [connect()] Sub connecting...
Traceback (most recent call last):
  File "examples/server.py", line 47, in <module>
    server(workq, resultq)
  File "examples/server.py", line 14, in server
    work_queue.send({"id": i, "cmd": f'echo "{i}"'})
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/wipac_telemetry/tracing_tools/spans.py", line 228, in wrapper
    return func(*args, **kwargs)
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient/queue.py", line 129, in send
    self.raw_pub_queue.send_message(msg)
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient/queue.py", line 74, in raw_pub_queue
    self._pub_queue = self._backend.create_pub_queue(
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient_rabbitmq/rabbitmq.py", line 361, in create_pub_queue
    q.connect()
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient_rabbitmq/rabbitmq.py", line 85, in connect
    super().connect()
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient_rabbitmq/rabbitmq.py", line 45, in connect
    pika.BlockingConnection(
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.IncompatibleProtocolError: StreamLostError: ('Transport indicated EOF',)
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.adapters.utils.io_services_utils[569780] ERROR Socket EOF; <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 48034)>
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.adapters.base_connection[569780] ERROR Transport indicated EOF.
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.adapters.base_connection[569780] ERROR connection_lost: StreamLostError: ('Transport indicated EOF',)
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.connection[569780] ERROR Probably incompatible Protocol Versions
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.adapters.utils.connection_workflow[569780] ERROR AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.adapters.utils.connection_workflow[569780] ERROR AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - None.
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.adapters.utils.connection_workflow[569780] ERROR AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - None
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.adapters.blocking_connection[569780] ERROR Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - None
2021-11-09 17:02:17 DellXPS-8BX90Z2 pika.adapters.blocking_connection[569780] ERROR Error in _create_connection().
Traceback (most recent call last):
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.IncompatibleProtocolError: StreamLostError: ('Transport indicated EOF',)
Traceback (most recent call last):
  File "examples/worker.py", line 36, in <module>
    worker(inq, outq)
  File "examples/worker.py", line 14, in worker
    with recv_queue.recv() as stream:
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient/queue.py", line 205, in recv
    return MessageGeneratorContext(self._create_sub_queue(), self)
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient/queue.py", line 95, in _create_sub_queue
    return self._backend.create_sub_queue(
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient_rabbitmq/rabbitmq.py", line 381, in create_sub_queue
    q.connect()
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient_rabbitmq/rabbitmq.py", line 143, in connect
    super().connect()
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient_rabbitmq/rabbitmq.py", line 45, in connect
    pika.BlockingConnection(
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.IncompatibleProtocolError: StreamLostError: ('Transport indicated EOF',)

```

**Comment by ric-evans** [comment]
running with `docker run -d --network=host deadtrickster/rabbitmq_prometheus` _without local wipactel_ produced:
```
2021-11-09 17:26:45 DellXPS-8BX90Z2 root[577491] DEBUG Creating new MessageGeneratorContext instance.
2021-11-09 17:26:45 DellXPS-8BX90Z2 root[577491] DEBUG [__init__()] Initializing sub. (('localhost', 'queue1'); {})
2021-11-09 17:26:45 DellXPS-8BX90Z2 root[577491] DEBUG [connect()] Sub connecting...
2021-11-09 17:26:45 DellXPS-8BX90Z2 root[577491] INFO Connecting with address=amqp://localhost
2021-11-09 17:26:45 DellXPS-8BX90Z2 pika.adapters.utils.io_services_utils[577491] ERROR Socket failed to connect: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 50724)>; error=111 (Connection refused)
2021-11-09 17:26:45 DellXPS-8BX90Z2 pika.adapters.utils.connection_workflow[577491] ERROR TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 5672))
2021-11-09 17:26:45 DellXPS-8BX90Z2 pika.adapters.utils.connection_workflow[577491] ERROR AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
2021-11-09 17:26:45 DellXPS-8BX90Z2 pika.adapters.utils.connection_workflow[577491] ERROR AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.
2021-11-09 17:26:45 DellXPS-8BX90Z2 pika.adapters.utils.connection_workflow[577491] ERROR AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None
2021-11-09 17:26:45 DellXPS-8BX90Z2 pika.adapters.blocking_connection[577491] ERROR Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None
2021-11-09 17:26:45 DellXPS-8BX90Z2 pika.adapters.blocking_connection[577491] ERROR Error in _create_connection().
Traceback (most recent call last):
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
Traceback (most recent call last):
  File "examples/worker.py", line 36, in <module>
    worker(inq, outq)
  File "examples/worker.py", line 14, in worker
    with recv_queue.recv() as stream:
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient/queue.py", line 205, in recv
    return MessageGeneratorContext(self._create_sub_queue(), self)
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient/queue.py", line 95, in _create_sub_queue
    return self._backend.create_sub_queue(
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient_rabbitmq/rabbitmq.py", line 377, in create_sub_queue
2021-11-09 17:26:45 DellXPS-8BX90Z2 root[577492] DEBUG [__init__()] Initializing pub. (('localhost', 'queue1'); {})
    q.connect()
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient_rabbitmq/rabbitmq.py", line 139, in connect
2021-11-09 17:26:45 DellXPS-8BX90Z2 root[577492] DEBUG [connect()] Pub connecting...
    super().connect()
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient_rabbitmq/rabbitmq.py", line 45, in connect
2021-11-09 17:26:45 DellXPS-8BX90Z2 root[577492] INFO Connecting with address=amqp://localhost
    self.connection = pika.BlockingConnection(
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2021-11-09 17:26:45 DellXPS-8BX90Z2 pika.adapters.utils.io_services_utils[577492] ERROR Socket failed to connect: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 50728)>; error=111 (Connection refused)
2021-11-09 17:26:45 DellXPS-8BX90Z2 pika.adapters.utils.connection_workflow[577492] ERROR TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 5672))
2021-11-09 17:26:45 DellXPS-8BX90Z2 pika.adapters.utils.connection_workflow[577492] ERROR AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
2021-11-09 17:26:45 DellXPS-8BX90Z2 pika.adapters.utils.connection_workflow[577492] ERROR AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None.
2021-11-09 17:26:45 DellXPS-8BX90Z2 pika.adapters.utils.connection_workflow[577492] ERROR AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None
2021-11-09 17:26:45 DellXPS-8BX90Z2 pika.adapters.blocking_connection[577492] ERROR Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - None
2021-11-09 17:26:45 DellXPS-8BX90Z2 pika.adapters.blocking_connection[577492] ERROR Error in _create_connection().
Traceback (most recent call last):
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
Traceback (most recent call last):
  File "examples/server.py", line 47, in <module>
    server(workq, resultq)
  File "examples/server.py", line 14, in server
    work_queue.send({"id": i, "cmd": f'echo "{i}"'})
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/wipac_telemetry/tracing_tools/spans.py", line 228, in wrapper
    return func(*args, **kwargs)
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient/queue.py", line 129, in send
    self.raw_pub_queue.send_message(msg)
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient/queue.py", line 74, in raw_pub_queue
    self._pub_queue = self._backend.create_pub_queue(
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient_rabbitmq/rabbitmq.py", line 357, in create_pub_queue
    q.connect()
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient_rabbitmq/rabbitmq.py", line 81, in connect
    super().connect()
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/mqclient_rabbitmq/rabbitmq.py", line 45, in connect
    self.connection = pika.BlockingConnection(
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/home/eevans/repos/MQClient-RabbitMQ/.tox/py/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError

```
